# Frontend Dockerfile
FROM python:3.12-slim

WORKDIR /app

COPY LICENSE.txt .
COPY README.md .
COPY pyproject.toml .
COPY src /app/src
COPY static /app/static

RUN pip install --upgrade pip

RUN pip install --no-cache-dir .


EXPOSE 8501

CMD ["streamlit", "run", "src/ui/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
