version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - OLLAMA_BASE_URL=http://172.17.0.1:11434
    volumes:
      - ./vectordb:/app/vectordb
    networks:
      - rag-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rag-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - rag-net

networks:
  rag-net:
    driver: bridge
