# Backend Dockerfile
FROM python:3.12-slim

WORKDIR /app

COPY src /app/src
COPY vectordb /app/vectordb
COPY LICENSE.txt .
COPY README.md .
COPY pyproject.toml .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir .

CMD ["uvicorn", "src.services.contract_app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
