networks:
  net:
    driver: bridge


services:
  vectordb:
    image: chromadb/chroma:latest
    # container_name: vectordb
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
      - CHROMA_SERVER_NOFILE=1048576
    ports:
      - "8010:8000"
    networks:
      - net
    # command: uvicorn chromadb.app:app --host 0.0.0.0 --port 8010 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30                               
  # cachingdb:
  #   image: chromadb/chroma:latest
  #   environment:
  #     - IS_PERSISTENT=FALSE
  #     - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-FALSE}
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - net
      # command: uvicorn chromadb.app:app --host 0.0.0.0 --port 8011 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30
  postgres_db:
      image: postgres:latest
      # container_name: postgres_db
      environment:
        POSTGRES_USER: postgres  # Default username
        POSTGRES_PASSWORD: postgres  # Default password
        POSTGRES_DB: postgres  # Default database name
      volumes:
        - ./data/postgres_data:/var/lpostgresib/postgresql/data  # Persist data
      ports:
        - "5432:5432"  # Expose Postgres port
      networks:
        - net
